name: get KBO data

on:
  schedule:
#    - cron: '45 14 * * *'
    - cron: '5 1 * * *'
    # UST 가 default라고 합니다.
    # 0시 5분에 돌아 가도록 했으니 한국 시간으로 9시 5분 실행됩니다.

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python package
      run: |
        pip install -r requirements.txt
    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Build
      run: |
        cd kbo_data
        python for_actions.py ${{secrets.API_URL}}
        cp *.json ../public/
# 위 Build에서 만든 파일을 아래 코드에서 gh-pages 브랜치를 만들고 저장한다.
# https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.KBO_DEPLOY }}
        publish_dir: ./public
